#!/system/bin/sh
# Remove '/system/lib/libjni_latinimegoogle.so'
#
# This fix force close of Google Keyboard
# after any 'GAPPS' install.
 
if [ -f /system/lib/libjni_latinimegoogle.so ]
then
	# Remount /system to read-write
	mount -o rw,remount /system
	# Remove lib of google latinime
	rm -rf /system/lib/libjni_latinimegoogle.so
	# Remount /system to original read-only
	mount -o ro,remount /system
fi
