#!/system/bin/sh
pm disable com.google.android.gms/.update.SystemUpdateActivity 
pm disable com.google.android.gms/.update.SystemUpdateService 
pm disable com.google.android.gms/.update.SystemUpdateService$ActiveReceiver 
pm disable com.google.android.gms/.update.SystemUpdateService$Receiver 
pm disable com.google.android.gms/.update.SystemUpdateService$SecretCodeReceiver 
pm disable com.google.android.gsf/.update.SystemUpdateActivity 
pm disable com.google.android.gsf/.update.SystemUpdatePanoActivity 
pm disable com.google.android.gsf/.update.SystemUpdateService 
pm disable com.google.android.gsf/.update.SystemUpdateService$Receiver 
pm disable com.google.android.gsf/.update.SystemUpdateService$SecretCodeReceiver
